### ISSUE TITLE
Seemingly duplicate parameter for age of eligibility of superannuation.

### ISSUE THREAD

**Issue by pserwylo** [ServiceInnovationLab/openfisca-aotearoa#131]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I am reviewing your code to learn more about openfisca, and in the process, I noticed two different definitions of the age in which someone is eligible for superannuation.

### Here is what I expected to happen:

Only one definition of the age of eligibilyt for superannuation.

### Here is what actually happened:

There is two definitions:

 * [`general/age_of_superannuation.yaml`](https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/master/openfisca_aotearoa/parameters/general/age_of_superannuation.yaml)
 * [`superannuation/age_qualification.yaml`](https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/master/openfisca_aotearoa/parameters/entitlements/superannuation/age_qualification.yaml).

Both reference the same legislation (with the latter being more specific due to deeplinking to the relevant part of the legislation:

 * http://www.legislation.govt.nz/act/public/2001/0084/latest/DLM113987.html#DLM113987

### Here is data (or links to it) that can help you reproduce this issue:

Each parameter is only used in one area each, respectively:

 * https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/fbd622c78186245d616ddf58e23441927852f64d/openfisca_aotearoa/variables/acts/super/super.py
https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/c2100b1b7f141591941cbb48bdba18828056beef/openfisca_aotearoa/variables/regulation/student_allowance/12/eligible.py

As a developer, I would prefer to use `entitlements.superannuation.age_qualification` rather than `general.age_of_superannuation`, as it is more semantically correct, and would allow grouping further parameters about superannuation in the future.

## Context

I identify more as a:

- Developer

**Comment by Br3nda** [comment]
Thank you for reporting this. Yes, i agree `entitlements.superannuation.age_qualification` is a duplicate and should go. To the best of my knowledge nobody is using that variable in a system.
