### ISSUE TITLE
All persons must be allocated to a titled_property.

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/openfisca-aotearoa#45]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

Requested `/calculate` to determine accommodation supplement.
this is my request body

```
{
  "persons": {
    "Tahi": {
      "social_security__eligible_for_accommodation_supplement": {
        "2018-08": null
      },
      "age": { "2018-08": 30},
      "normally_lives_in_nz": { "2018-08": true },
      "is_resident": { "2018-08":  true },
      "has_accomodation_costs": { "2018-08":  true },
      "eligible_for_social_housing": { "2018-08": false},
      "income_below_threshold_for_accommodation_supplement": { "2018-08":  true},
      "cash_below_threshold_for_accommodation_supplement": { "2018-08": true}
    }
  },
  "families": {
  	"first": {
  		"principal_caregiver": ["Tahi"]
  	}
  }
}
```

### Here is what I expected to happen:

I expected it to tell me if they are eligible for accommodation supplement.

```
            "social_security__eligible_for_accommodation_supplement": {
                "2018-08": true
            }
```

### Here is what actually happened:

I get this error back

```
{
   "titled_properties":  "Tahi has been declared in persons, but is not a member of any titled_property. All persons must be allocated to a titled_property."
 }
```

### Here is data (or links to it) that can help you reproduce this issue:

The (hypothetical) applicant doesn't own any "titled_property". Why do we need to add them to a property? 

needs openfisca/openfisca-core#667

**Comment by Br3nda** [comment]
I got a similar message about all person needing to be in a family

**Comment by MattiSG** [comment]
Yes, this is https://github.com/openfisca/openfisca-core/issues/667.

**Comment by Br3nda** [comment]
cool marking as:
needs openfisca/openfisca-core#667

**Comment by Br3nda** [comment]
@verbman it feels very wrong to allocate people as an owner of a house before they can get a disability payment. I'm thinking i make some other roles that people can be  in a house, instead of being an owner. e.g. a "member" of "default_household"

**Comment by verbman** [comment]
@Br3nda - I agree - if we name a role specifically for when a role isn't required. There's been discussion at OpenFisca Core of making a change so these roles might not be required in the future. If that ever became a reality it'd make it easier to identify and tidy up these otherwise not needed relationships.

**Comment by Br3nda** [comment]
created as #48
