### ISSUE TITLE
sole_parent__family_has_child_under_age_limit

### ISSUE THREAD

**Issue by verbman** [ServiceInnovationLab/openfisca-aotearoa#89]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

For consistency we should rename the variable `sole_parent__family_has_child_under_age_limit` to `sole_parent_support__family_has_child_under_age_limit' to match the other associated variables.

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Br3nda** [comment]
This would be a breaking change for smart start, so we've not proceeded.
